# Makefile for programming the ATtiny85
# modified the one generated by CrossPack

DEVICE      = attiny85
CLOCK      = 1000000
PROGRAMMER = -c usbtiny 
OBJECTS    = ps2convergent.o ser_recv.c
# for ATTiny85
# see http://www.engbedded.com/fusecalc/
FUSES       = -U lfuse:w:0x62:m -U hfuse:w:0xdf:m -U efuse:w:0xff:m 

# Tune the lines below only if you know what you are doing:
AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
COMPILE = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

# symbolic targets:
all:	ps2convergent.hex

scancode_list:
	python ./gen_convergent_scancodes.py > convergent_scancode_list.py

scancode:
	python ./scott_convergentmapgen.py > convergent_scancode_map.h

.c.o:
	$(COMPILE) -c $< -o $@

.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@

.c.s:
	$(COMPILE) -S $< -o $@

flash:	all
	$(AVRDUDE) -U flash:w:ps2convergent.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID ps2convergent.hex

clean:
	rm -f ps2convergent.hex ps2convergent.elf $(OBJECTS)

# file targets:
ps2convergent.elf: $(OBJECTS)
	$(COMPILE) -o ps2convergent.elf $(OBJECTS)

ps2convergent.hex: ps2convergent.elf
	rm -f ps2convergent.hex
	avr-objcopy -j .text -j .data -O ihex ps2convergent.elf ps2convergent.hex
#	avr-size ps2convergent.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	ps2convergent.elf
	avr-objdump -d ps2convergent.elf
