# NOTE: Customize the following to your environment!

AVR_TOOLS_DIR = /usr
ARDUINO_DIR=/home/smbaker/projects/pi/arduino
ARDUINO_MK_FILE=/usr/share/arduino/Arduino.mk

ISP_PROG=usbasp

BOARD_TAG=atmega328bb
ISP_HIGH_FUSE = 0xDF
ISP_LOW_FUSE = 0xE2
ISP_EXT_FUSE = 0xFF


# Scott's old makefile, runs avrdude directly using "make flash" or "make fuse"
DEVICE     = m328
CLOCK      = 8000000
PROGRAMMER = -c usbtiny 
FUSES       = -U lfuse:w:0xE2:m -U hfuse:w:0xdf:m -U efuse:w:0xff:m 
AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)


old-flash:
	$(AVRDUDE) -B 3 -c usbasp -U flash:w:convergent-kbd-at328.ino.arduino_standard.hex:i

old-fuse:
	$(AVRDUDE) -B 3 -c usbasp $(FUSES)

include $(ARDUINO_MK_FILE)
