scancode_list:
	python ./gen_convergent_scancodes.py > convergent_scancode_list.py

scancode:
	python ./scott_convergentmapgen.py > convergent_scancode_map.h
	cp convergent_scancode_map.h ../convergent-kbd-tiny85/
